name: Build Multi-Platform Container

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: true
        default: 'latest'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Linux images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/386,linux/ppc64le,linux/s390x
          push: true
          tags: jaysharma3/mcp-instana:${{ github.event.inputs.tag }}-linux

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Windows image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.windows
          platforms: windows/amd64
          push: true
          tags: jaysharma3/mcp-instana:${{ github.event.inputs.tag }}-windows

  create-manifest:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create and push manifest
        run: |
          docker manifest create jaysharma3/mcp-instana:${{ github.event.inputs.tag }} \
            jaysharma3/mcp-instana:${{ github.event.inputs.tag }}-linux \
            jaysharma3/mcp-instana:${{ github.event.inputs.tag }}-windows
          
          docker manifest push jaysharma3/mcp-instana:${{ github.event.inputs.tag }}
