name: Build Multi-Platform Container

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Windows image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.windows
          platforms: windows/amd64
          push: true
          tags: jaysharma3/mcp-instana:${{ github.event.inputs.tag }}-windows

      - name: Create and push manifest
        if: success()
        shell: bash
        run: |
          # Pull the Linux image to check if it exists
          if docker manifest inspect jaysharma3/mcp-instana:${{ github.event.inputs.tag }}-linux > /dev/null 2>&1; then
            echo "Creating manifest with both Linux and Windows images"
            docker manifest create jaysharma3/mcp-instana:${{ github.event.inputs.tag }} \
              jaysharma3/mcp-instana:${{ github.event.inputs.tag }}-linux \
              jaysharma3/mcp-instana:${{ github.event.inputs.tag }}-windows
            docker manifest push jaysharma3/mcp-instana:${{ github.event.inputs.tag }}
          else
            echo "Linux image not found. Creating manifest with Windows image only"
            docker manifest create jaysharma3/mcp-instana:${{ github.event.inputs.tag }}-windows-only \
              jaysharma3/mcp-instana:${{ github.event.inputs.tag }}-windows
            docker manifest push jaysharma3/mcp-instana:${{ github.event.inputs.tag }}-windows-only
          fi
